AWSTemplateFormatVersion: 2010-09-09
Description: 'Deploy Exam JS Application'
Resources: 
  ExamJSApp:
    Type: AWS::ElasticBeanstalk::Application
    Properties: 
      ApplicationName: 'ExamJS'
      Description: 'Application for the Exam JS project'
  MainEnv:
    Type: AWS::ElasticBeanstalk::Environment
    Properties: 
      ApplicationName: !Ref ExamJSApp
      CNAMEPrefix: 'exam'
      Description: 'Main component of the App - Web server that manage all public resources'
      EnvironmentName: 'MainServer'
      TemplateName: !Ref MainEnvTemplate
      VersionLabel: !Ref MainEnvSource
      Tier: 
        Name: WebServer
        Type: Standard
  MainEnvSource:
    Type: AWS::ElasticBeanstalk::ApplicationVersion
    Properties:
      ApplicationName: !Ref ExamJSApp
      Description: 'Source code of Main Env server'
      SourceBundle:
        S3Bucket: 'examjs'
        S3Key: 'mainenv/ExamGame-0.3.6.zip'
  MainEnvTemplate:
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
    Properties:
      ApplicationName: !Ref ExamJSApp
      Description: 'ElasticBeanstalk template for MainEnv'
      SolutionStackName: 64bit Amazon Linux 2018.03 v4.9.2 running Node.js
      OptionSettings:
      - Namespace: aws:autoscaling:asg
        OptionName: MinSize
        Value: '1'
      - Namespace: aws:autoscaling:asg
        OptionName: MaxSize
        Value: '2'
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: EC2KeyName
        Value: '2IrelandKeyPair'
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: IamInstanceProfile
        Value: 'aws-elasticbeanstalk-ec2-role'
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: SecurityGroups
        Value: 'sg-098232a19bad70019'
      - Namespace: aws:elasticbeanstalk:environment
        OptionName: EnvironmentType
        Value: 'LoadBalanced'
      - Namespace: aws:elasticbeanstalk:environment
        OptionName: LoadBalancerType
        Value: 'application'
      - Namespace: aws:elasticbeanstalk:environment:process:default
        OptionName: Port
        Value: '8081'
      - Namespace: aws:elasticbeanstalk:environment:process:redirectprocess
        OptionName: Port
        Value: '4432'
      - Namespace: aws:elasticbeanstalk:environment:process:redirectprocess
        OptionName: MatcherHTTPCode
        Value: '302'
      - Namespace: aws:elbv2:listener:default
        OptionName: DefaultProcess
        Value: 'redirectprocess'
      - Namespace: aws:elbv2:listener:443
        OptionName: Protocol
        Value: 'HTTPS'
      - Namespace: aws:elbv2:listener:443
        OptionName: DefaultProcess
        Value: 'default'
      - Namespace: aws:elbv2:listener:443
        OptionName: SSLCertificateArns
        Value: 'arn:aws:acm:eu-west-1:698833950932:certificate/4118c363-247b-4119-9758-ba68c8952107'
      - Namespace: aws:ec2:vpc
        OptionName: VPCId
        Value: 'vpc-99745eff'
      - Namespace: aws:ec2:vpc
        OptionName: Subnets
        Value: 'subnet-906e19d8, subnet-51e98d37'
  MirrorSharpEnv:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName: !Ref ExamJSApp
      CNAMEPrefix: 'sharp'
      Description: 'Server for C# autocompletion and intellisense'
      EnvironmentName: 'MirrorSharp'
      TemplateName: !Ref MirrorSharpEnvTemplate
      VersionLabel: !Ref MirrorSharpEnvSource
      Tier:
        Name: WebServer
        Type: Standard
  MirrorSharpEnvSource:
    Type: AWS::ElasticBeanstalk::ApplicationVersion
    Properties:
      ApplicationName: !Ref ExamJSApp
      Description: 'Source code of Mirror Sharp server'
      SourceBundle:
        S3Bucket: 'examjs'
        S3Key: 'mirrorsharp/MirrorSharp-0.3.2.zip'
  MirrorSharpEnvTemplate:
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
    Properties:
      ApplicationName: !Ref ExamJSApp
      Description: 'ElasticBeanstalk template for MirrorSharp'
      SolutionStackName: 64bit Windows Server 2016 v2.1.0 running IIS 10.0
      OptionSettings:
      - Namespace: aws:autoscaling:asg
        OptionName: MinSize
        Value: '1'
      - Namespace: aws:autoscaling:asg
        OptionName: MaxSize
        Value: '2'
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: EC2KeyName
        Value: '2IrelandKeyPair'
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: IamInstanceProfile
        Value: 'aws-elasticbeanstalk-ec2-role'
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: SecurityGroups
        Value: 'sg-098232a19bad70019'
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: InstanceType
        Value: 't2.micro'
      - Namespace: aws:elasticbeanstalk:environment
        OptionName: EnvironmentType
        Value: 'LoadBalanced'
      - Namespace: aws:elasticbeanstalk:environment
        OptionName: LoadBalancerType
        Value: 'application'
      - Namespace: aws:elasticbeanstalk:environment:process:default
        OptionName: Port
        Value: '80'
      - Namespace: aws:elasticbeanstalk:environment:process:default
        OptionName: HealthCheckPath
        Value: '/mirrorsharp'
      - Namespace: aws:elbv2:listener:default
        OptionName: DefaultProcess
        Value: 'default'
      - Namespace: aws:elbv2:listener:443
        OptionName: Protocol
        Value: 'HTTPS'
      - Namespace: aws:elbv2:listener:443
        OptionName: DefaultProcess
        Value: 'default'
      - Namespace: aws:elbv2:listener:443
        OptionName: SSLCertificateArns
        Value: 'arn:aws:acm:eu-west-1:698833950932:certificate/378934ec-9e82-45bd-a7bd-65db636c307f'
      - Namespace: aws:ec2:vpc
        OptionName: VPCId
        Value: 'vpc-99745eff'
      - Namespace: aws:ec2:vpc
        OptionName: Subnets
        Value: 'subnet-906e19d8, subnet-51e98d37'